import fs from "node:fs/promises";
import path from "node:path";

import type { CommandContext } from "../types.js";
import { CliError } from "../core/errors.js";
import { pathExists } from "../core/fs.js";
import { buildThreadBrief, readVoiceContextEvents, type VoiceContextEvent } from "../core/voice-context.js";

export async function replayCommand(context: CommandContext, args: string[]): Promise<void> {
  const action = args[0] ?? "help";

  if (action === "help" || action === "--help" || action === "-h") {
    printReplayHelp(context);
    return;
  }

  if (action === "export") {
    await exportReplay(context, args.slice(1));
    return;
  }

  throw new CliError(`Unknown replay command: ${action}`);
}

async function exportReplay(context: CommandContext, args: string[]): Promise<void> {
  const outputDir = path.resolve(args[0] ?? path.join(process.cwd(), "codex-thread-replay"));
  const events = await readVoiceContextEvents(context.paths.classroomRoot, 120);
  if (events.length === 0) {
    throw new CliError("No Codex Voice context events found. Run codex-classroom voice install-hook and record a thread first.");
  }

  if ((await pathExists(outputDir)) && !context.options.force) {
    throw new CliError(`Output directory already exists: ${outputDir}. Use --force to overwrite generated files.`);
  }

  await fs.mkdir(path.join(outputDir, "src", "data"), { recursive: true });
  await fs.writeFile(path.join(outputDir, "package.json"), `${JSON.stringify(buildPackageJson(), null, 2)}\n`, "utf8");
  await fs.writeFile(path.join(outputDir, "README.md"), buildReplayReadme(events), "utf8");
  await fs.writeFile(path.join(outputDir, "tsconfig.json"), buildTsconfig(), "utf8");
  await fs.writeFile(path.join(outputDir, "remotion.config.ts"), buildRemotionConfig(), "utf8");
  await fs.writeFile(path.join(outputDir, "src", "index.ts"), buildIndexTs(), "utf8");
  await fs.writeFile(path.join(outputDir, "src", "Root.tsx"), buildRootTsx(events), "utf8");
  await fs.writeFile(path.join(outputDir, "src", "Replay.tsx"), buildReplayTsx(), "utf8");
  await fs.writeFile(path.join(outputDir, "src", "data", "events.json"), `${JSON.stringify(events, null, 2)}\n`, "utf8");
  await fs.writeFile(path.join(outputDir, "src", "data", "brief.txt"), `${buildThreadBrief(events, 24)}\n`, "utf8");

  if (context.options.json) {
    context.output.json({ ok: true, outputDir, events: events.length });
    return;
  }

  context.output.info(`Exported Remotion replay project to ${outputDir}`);
  context.output.info(`Events: ${events.length}`);
  context.output.info("Next:");
  context.output.info(`  cd ${outputDir}`);
  context.output.info("  npm install");
  context.output.info("  npm run preview");
  context.output.info("  npm run render");
}

function buildPackageJson(): Record<string, unknown> {
  return {
    private: true,
    name: "codex-thread-replay",
    version: "0.1.0",
    type: "module",
    scripts: {
      preview: "remotion studio",
      render: "remotion render CodexThreadReplay out/codex-thread-replay.mp4",
      still: "remotion still CodexThreadReplay --frame=90 out/preview.png",
    },
    dependencies: {
      "@remotion/cli": "latest",
      remotion: "latest",
      react: "latest",
      "react-dom": "latest",
    },
    devDependencies: {
      "@types/react": "latest",
      "@types/react-dom": "latest",
      typescript: "latest",
    },
  };
}

function buildReplayReadme(events: VoiceContextEvent[]): string {
  return `# Codex Thread Replay

This folder was generated by \`codex-classroom replay export\`.

It renders a Remotion video from Codex Voice context events. The source data is in \`src/data/events.json\`.

## Preview

\`\`\`sh
npm install
npm run preview
\`\`\`

## Render

\`\`\`sh
npm run render
\`\`\`

The rendered file is written to \`out/codex-thread-replay.mp4\`.

## Source Summary

Events: ${events.length}

${buildThreadBrief(events, 16)}
`;
}

function buildTsconfig(): string {
  return `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx"
  },
  "include": ["src", "remotion.config.ts"]
}
`;
}

function buildRemotionConfig(): string {
  return `import { Config } from "@remotion/cli/config";

Config.setVideoImageFormat("jpeg");
Config.setOverwriteOutput(true);
`;
}

function buildIndexTs(): string {
  return `import { registerRoot } from "remotion";
import { RemotionRoot } from "./Root";

registerRoot(RemotionRoot);
`;
}

function buildRootTsx(events: VoiceContextEvent[]): string {
  const durationInFrames = Math.max(240, events.length * 90 + 120);
  return `import { Composition } from "remotion";
import { Replay } from "./Replay";
import events from "./data/events.json";

export type ReplayEvent = {
  schemaVersion: 1;
  id: string;
  at: string;
  source: string;
  kind: string;
  title: string;
  summary: string;
  cwd?: string;
  toolName?: string;
  command?: string;
  status?: string;
};

export const RemotionRoot = () => {
  return (
    <Composition
      id="CodexThreadReplay"
      component={Replay}
      durationInFrames={${durationInFrames}}
      fps={30}
      width={1920}
      height={1080}
      defaultProps={{
        events: events as ReplayEvent[],
      }}
    />
  );
};
`;
}

function buildReplayTsx(): string {
  return `import type { CSSProperties } from "react";
import { AbsoluteFill, Easing, interpolate, useCurrentFrame, useVideoConfig } from "remotion";
import type { ReplayEvent } from "./Root";

export type ReplayProps = {
  events: ReplayEvent[];
};

const eventColors: Record<string, string> = {
  "user-prompt": "#f0c36a",
  "tool-result": "#7fd1ae",
  "turn-complete": "#8fb8ff",
  started: "#f0c36a",
  changed: "#7fd1ae",
  blocked: "#ff8a8a",
  verified: "#8fb8ff",
  note: "#d8d2c4",
};

export const Replay = ({ events }: ReplayProps) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const introFrames = 60;
  const eventFrames = 90;
  const activeIndex = Math.min(
    Math.max(0, Math.floor((frame - introFrames) / eventFrames)),
    Math.max(0, events.length - 1),
  );
  const active = events[activeIndex];
  const progress = interpolate(frame, [0, durationInFrames - 1], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const localFrame = Math.max(0, frame - introFrames - activeIndex * eventFrames);
  const enter = interpolate(localFrame, [0, 24], [0, 1], {
    easing: Easing.bezier(0.16, 1, 0.3, 1),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  if (!active) {
    return (
      <AbsoluteFill style={styles.root}>
        <div style={styles.empty}>No replay events were recorded.</div>
      </AbsoluteFill>
    );
  }

  const visibleEvents = events.slice(Math.max(0, activeIndex - 4), activeIndex + 1);
  const color = eventColors[active.kind] ?? "#d8d2c4";

  return (
    <AbsoluteFill style={styles.root}>
      <div style={styles.progressTrack}>
        <div style={{ ...styles.progressFill, width: String(progress * 100) + "%" }} />
      </div>

      <div style={styles.header}>
        <div>
          <div style={styles.eyebrow}>Codex Classroom Replay</div>
          <h1 style={styles.title}>Thread Replay</h1>
        </div>
        <div style={styles.counter}>
          {activeIndex + 1} / {events.length}
        </div>
      </div>

      <div style={styles.layout}>
        <section
          style={{
            ...styles.hero,
            borderColor: color,
            opacity: enter,
            transform: "translateY(" + (24 - enter * 24) + "px)",
          }}
        >
          <div style={{ ...styles.kind, color }}>{active.kind}</div>
          <h2 style={styles.eventTitle}>{active.title}</h2>
          <p style={styles.summary}>{active.summary}</p>
          <div style={styles.metaGrid}>
            <Meta label="Time" value={new Date(active.at).toLocaleTimeString()} />
            <Meta label="Source" value={active.source} />
            <Meta label="Tool" value={active.toolName ?? "n/a"} />
            <Meta label="Status" value={active.status ?? "n/a"} />
          </div>
          {active.command ? <pre style={styles.command}>{active.command}</pre> : null}
        </section>

        <aside style={styles.timeline}>
          {visibleEvents.map((event, index) => {
            const selected = index === visibleEvents.length - 1;
            return (
              <div key={event.id} style={{ ...styles.timelineItem, opacity: selected ? 1 : 0.62 }}>
                <div style={{ ...styles.dot, background: eventColors[event.kind] ?? "#d8d2c4" }} />
                <div>
                  <div style={styles.timelineKind}>{event.kind}</div>
                  <div style={styles.timelineTitle}>{event.title}</div>
                </div>
              </div>
            );
          })}
        </aside>
      </div>

      <div style={styles.footer}>
        Generated from Codex Voice context events at {fps} fps
      </div>
    </AbsoluteFill>
  );
};

const Meta = ({ label, value }: { label: string; value: string }) => (
  <div style={styles.meta}>
    <div style={styles.metaLabel}>{label}</div>
    <div style={styles.metaValue}>{value}</div>
  </div>
);

const styles: Record<string, CSSProperties> = {
  root: {
    background: "#141414",
    color: "#f4efe6",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    padding: 72,
  },
  progressTrack: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 10,
    background: "#2b2924",
  },
  progressFill: {
    height: "100%",
    background: "#f0c36a",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 48,
  },
  eyebrow: {
    color: "#b8afa2",
    fontSize: 28,
  },
  title: {
    fontSize: 88,
    lineHeight: 1,
    margin: "8px 0 0",
    letterSpacing: 0,
  },
  counter: {
    border: "1px solid #4b453c",
    borderRadius: 8,
    padding: "16px 22px",
    color: "#d8d2c4",
    fontSize: 28,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "1fr 520px",
    gap: 36,
    minHeight: 650,
  },
  hero: {
    border: "3px solid #f0c36a",
    borderRadius: 8,
    background: "#1f1d19",
    padding: 48,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  kind: {
    fontSize: 30,
    textTransform: "uppercase",
    fontWeight: 700,
    marginBottom: 16,
  },
  eventTitle: {
    fontSize: 68,
    lineHeight: 1.05,
    margin: "0 0 24px",
    letterSpacing: 0,
  },
  summary: {
    fontSize: 34,
    lineHeight: 1.35,
    color: "#ddd5c8",
    margin: "0 0 34px",
  },
  metaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 12,
  },
  meta: {
    border: "1px solid #403b34",
    borderRadius: 8,
    padding: 16,
    minWidth: 0,
  },
  metaLabel: {
    color: "#9d9588",
    fontSize: 20,
    marginBottom: 8,
  },
  metaValue: {
    color: "#f4efe6",
    fontSize: 23,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  command: {
    marginTop: 28,
    padding: 18,
    borderRadius: 8,
    background: "#111",
    border: "1px solid #403b34",
    color: "#d8d2c4",
    fontSize: 22,
    whiteSpace: "pre-wrap",
  },
  timeline: {
    border: "1px solid #403b34",
    borderRadius: 8,
    background: "#1b1a17",
    padding: 26,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 20,
  },
  timelineItem: {
    display: "grid",
    gridTemplateColumns: "18px 1fr",
    gap: 16,
    alignItems: "start",
  },
  dot: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    marginTop: 7,
  },
  timelineKind: {
    color: "#9d9588",
    fontSize: 20,
    textTransform: "uppercase",
  },
  timelineTitle: {
    color: "#f4efe6",
    fontSize: 26,
    lineHeight: 1.2,
  },
  footer: {
    position: "absolute",
    left: 72,
    bottom: 42,
    color: "#8e8679",
    fontSize: 24,
  },
  empty: {
    margin: "auto",
    fontSize: 44,
  },
};
`;
}

function printReplayHelp(context: CommandContext): void {
  context.output.info(`codex-classroom replay

Usage:
  codex-classroom replay export [output-dir] [options]

Commands:
  export    Generate a Remotion replay project from Codex Voice context events

Options:
  --force   Overwrite generated files in an existing output directory
  --json    Emit machine-readable output
`);
}
